// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Awnz-7FlzXa_mbggUFeoSEseHB33Nl8',
    appId: '1:1012332903940:web:063f6666e8a32a84187f51',
    messagingSenderId: '1012332903940',
    projectId: 'productiv-349e6',
    authDomain: 'productiv-349e6.firebaseapp.com',
    storageBucket: 'productiv-349e6.appspot.com',
    measurementId: 'G-NRRRS3VN20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdEqAuzaRkDmgohwdc7O0ETYl4fzjTINo',
    appId: '1:1012332903940:android:3a2e5eaf1670876f187f51',
    messagingSenderId: '1012332903940',
    projectId: 'gproductiv-349e6',
    storageBucket: 'productiv-349e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl0Pg545vsQEMkCvwij3hRcRWxfuxqMys',
    appId: '1:1012332903940:ios:b1715ef3e92e3e2b187f51',
    messagingSenderId: '1012332903940',
    projectId: 'productiv-349e6',
    storageBucket: 'productiv-349e6.appspot.com',
    iosBundleId: 'com.example.produktiv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl0Pg545vsQEMkCvwij3hRcRWxfuxqMys',
    appId: '1:1012332903940:ios:170b214548bdfd32187f51',
    messagingSenderId: '1012332903940',
    projectId: 'productiv-349e6',
    storageBucket: 'productiv-349e6.appspot.com',
    iosBundleId: 'com.example.produktiv.RunnerTests',
  );
}
